version: '3'

services:
  reverse-proxy:
    container_name: reverse_proxy_nginx
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app:
    container_name: container_springboot
    restart: always
    image: demo-spring-app:0.0.1-SNAPSHOT
    ports:
      - 8081:8081
    expose:
      - 8081
