version: '3'

services:
  reverse-proxy:
    container_name: reverse_proxy_nginx
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  side-car-spring:
    container_name: side-car-spring
    restart: always
    image: side-car-spring:0.0.1
    ports:
      - 8081:8081
